// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient.proto

package com.axxes.data.protos;

public final class PatientProtos {
  private PatientProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code AnnotationType}
   */
  public enum AnnotationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>afib = 0;</code>
     */
    afib(0),
    /**
     * <code>pause = 1;</code>
     */
    pause(1),
    /**
     * <code>brady = 2;</code>
     */
    brady(2),
    /**
     * <code>tachy = 3;</code>
     */
    tachy(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>afib = 0;</code>
     */
    public static final int afib_VALUE = 0;
    /**
     * <code>pause = 1;</code>
     */
    public static final int pause_VALUE = 1;
    /**
     * <code>brady = 2;</code>
     */
    public static final int brady_VALUE = 2;
    /**
     * <code>tachy = 3;</code>
     */
    public static final int tachy_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AnnotationType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AnnotationType forNumber(int value) {
      switch (value) {
        case 0: return afib;
        case 1: return pause;
        case 2: return brady;
        case 3: return tachy;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AnnotationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AnnotationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AnnotationType>() {
            public AnnotationType findValueByNumber(int number) {
              return AnnotationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.axxes.data.protos.PatientProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final AnnotationType[] VALUES = values();

    public static AnnotationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AnnotationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AnnotationType)
  }

  public interface AnnotationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Annotation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>float start = 2;</code>
     * @return The start.
     */
    float getStart();

    /**
     * <code>float end = 3;</code>
     * @return The end.
     */
    float getEnd();

    /**
     * <code>.AnnotationType annotation_type = 4;</code>
     * @return The enum numeric value on the wire for annotationType.
     */
    int getAnnotationTypeValue();
    /**
     * <code>.AnnotationType annotation_type = 4;</code>
     * @return The annotationType.
     */
    com.axxes.data.protos.PatientProtos.AnnotationType getAnnotationType();
  }
  /**
   * Protobuf type {@code Annotation}
   */
  public static final class Annotation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Annotation)
      AnnotationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Annotation.newBuilder() to construct.
    private Annotation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Annotation() {
      id_ = "";
      annotationType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Annotation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Annotation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 21: {

              start_ = input.readFloat();
              break;
            }
            case 29: {

              end_ = input.readFloat();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              annotationType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.axxes.data.protos.PatientProtos.internal_static_Annotation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.axxes.data.protos.PatientProtos.internal_static_Annotation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.axxes.data.protos.PatientProtos.Annotation.class, com.axxes.data.protos.PatientProtos.Annotation.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 2;
    private float start_;
    /**
     * <code>float start = 2;</code>
     * @return The start.
     */
    @java.lang.Override
    public float getStart() {
      return start_;
    }

    public static final int END_FIELD_NUMBER = 3;
    private float end_;
    /**
     * <code>float end = 3;</code>
     * @return The end.
     */
    @java.lang.Override
    public float getEnd() {
      return end_;
    }

    public static final int ANNOTATION_TYPE_FIELD_NUMBER = 4;
    private int annotationType_;
    /**
     * <code>.AnnotationType annotation_type = 4;</code>
     * @return The enum numeric value on the wire for annotationType.
     */
    @java.lang.Override public int getAnnotationTypeValue() {
      return annotationType_;
    }
    /**
     * <code>.AnnotationType annotation_type = 4;</code>
     * @return The annotationType.
     */
    @java.lang.Override public com.axxes.data.protos.PatientProtos.AnnotationType getAnnotationType() {
      @SuppressWarnings("deprecation")
      com.axxes.data.protos.PatientProtos.AnnotationType result = com.axxes.data.protos.PatientProtos.AnnotationType.valueOf(annotationType_);
      return result == null ? com.axxes.data.protos.PatientProtos.AnnotationType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (java.lang.Float.floatToRawIntBits(start_) != 0) {
        output.writeFloat(2, start_);
      }
      if (java.lang.Float.floatToRawIntBits(end_) != 0) {
        output.writeFloat(3, end_);
      }
      if (annotationType_ != com.axxes.data.protos.PatientProtos.AnnotationType.afib.getNumber()) {
        output.writeEnum(4, annotationType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (java.lang.Float.floatToRawIntBits(start_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, start_);
      }
      if (java.lang.Float.floatToRawIntBits(end_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, end_);
      }
      if (annotationType_ != com.axxes.data.protos.PatientProtos.AnnotationType.afib.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, annotationType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.axxes.data.protos.PatientProtos.Annotation)) {
        return super.equals(obj);
      }
      com.axxes.data.protos.PatientProtos.Annotation other = (com.axxes.data.protos.PatientProtos.Annotation) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (java.lang.Float.floatToIntBits(getStart())
          != java.lang.Float.floatToIntBits(
              other.getStart())) return false;
      if (java.lang.Float.floatToIntBits(getEnd())
          != java.lang.Float.floatToIntBits(
              other.getEnd())) return false;
      if (annotationType_ != other.annotationType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStart());
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEnd());
      hash = (37 * hash) + ANNOTATION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + annotationType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.axxes.data.protos.PatientProtos.Annotation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.axxes.data.protos.PatientProtos.Annotation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Annotation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Annotation)
        com.axxes.data.protos.PatientProtos.AnnotationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.axxes.data.protos.PatientProtos.internal_static_Annotation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.axxes.data.protos.PatientProtos.internal_static_Annotation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.axxes.data.protos.PatientProtos.Annotation.class, com.axxes.data.protos.PatientProtos.Annotation.Builder.class);
      }

      // Construct using com.axxes.data.protos.PatientProtos.Annotation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        start_ = 0F;

        end_ = 0F;

        annotationType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.axxes.data.protos.PatientProtos.internal_static_Annotation_descriptor;
      }

      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.Annotation getDefaultInstanceForType() {
        return com.axxes.data.protos.PatientProtos.Annotation.getDefaultInstance();
      }

      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.Annotation build() {
        com.axxes.data.protos.PatientProtos.Annotation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.Annotation buildPartial() {
        com.axxes.data.protos.PatientProtos.Annotation result = new com.axxes.data.protos.PatientProtos.Annotation(this);
        result.id_ = id_;
        result.start_ = start_;
        result.end_ = end_;
        result.annotationType_ = annotationType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.axxes.data.protos.PatientProtos.Annotation) {
          return mergeFrom((com.axxes.data.protos.PatientProtos.Annotation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.axxes.data.protos.PatientProtos.Annotation other) {
        if (other == com.axxes.data.protos.PatientProtos.Annotation.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getStart() != 0F) {
          setStart(other.getStart());
        }
        if (other.getEnd() != 0F) {
          setEnd(other.getEnd());
        }
        if (other.annotationType_ != 0) {
          setAnnotationTypeValue(other.getAnnotationTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.axxes.data.protos.PatientProtos.Annotation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.axxes.data.protos.PatientProtos.Annotation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private float start_ ;
      /**
       * <code>float start = 2;</code>
       * @return The start.
       */
      @java.lang.Override
      public float getStart() {
        return start_;
      }
      /**
       * <code>float start = 2;</code>
       * @param value The start to set.
       * @return This builder for chaining.
       */
      public Builder setStart(float value) {
        
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float start = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStart() {
        
        start_ = 0F;
        onChanged();
        return this;
      }

      private float end_ ;
      /**
       * <code>float end = 3;</code>
       * @return The end.
       */
      @java.lang.Override
      public float getEnd() {
        return end_;
      }
      /**
       * <code>float end = 3;</code>
       * @param value The end to set.
       * @return This builder for chaining.
       */
      public Builder setEnd(float value) {
        
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float end = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnd() {
        
        end_ = 0F;
        onChanged();
        return this;
      }

      private int annotationType_ = 0;
      /**
       * <code>.AnnotationType annotation_type = 4;</code>
       * @return The enum numeric value on the wire for annotationType.
       */
      @java.lang.Override public int getAnnotationTypeValue() {
        return annotationType_;
      }
      /**
       * <code>.AnnotationType annotation_type = 4;</code>
       * @param value The enum numeric value on the wire for annotationType to set.
       * @return This builder for chaining.
       */
      public Builder setAnnotationTypeValue(int value) {
        
        annotationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.AnnotationType annotation_type = 4;</code>
       * @return The annotationType.
       */
      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.AnnotationType getAnnotationType() {
        @SuppressWarnings("deprecation")
        com.axxes.data.protos.PatientProtos.AnnotationType result = com.axxes.data.protos.PatientProtos.AnnotationType.valueOf(annotationType_);
        return result == null ? com.axxes.data.protos.PatientProtos.AnnotationType.UNRECOGNIZED : result;
      }
      /**
       * <code>.AnnotationType annotation_type = 4;</code>
       * @param value The annotationType to set.
       * @return This builder for chaining.
       */
      public Builder setAnnotationType(com.axxes.data.protos.PatientProtos.AnnotationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        annotationType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.AnnotationType annotation_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnnotationType() {
        
        annotationType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Annotation)
    }

    // @@protoc_insertion_point(class_scope:Annotation)
    private static final com.axxes.data.protos.PatientProtos.Annotation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.axxes.data.protos.PatientProtos.Annotation();
    }

    public static com.axxes.data.protos.PatientProtos.Annotation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Annotation>
        PARSER = new com.google.protobuf.AbstractParser<Annotation>() {
      @java.lang.Override
      public Annotation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Annotation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Annotation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Annotation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.axxes.data.protos.PatientProtos.Annotation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Patient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hospitalId = 1;</code>
     * @return The hospitalId.
     */
    java.lang.String getHospitalId();
    /**
     * <code>string hospitalId = 1;</code>
     * @return The bytes for hospitalId.
     */
    com.google.protobuf.ByteString
        getHospitalIdBytes();

    /**
     * <code>string patientId = 2;</code>
     * @return The patientId.
     */
    java.lang.String getPatientId();
    /**
     * <code>string patientId = 2;</code>
     * @return The bytes for patientId.
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();

    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @return A list containing the sensorDots.
     */
    java.util.List<java.lang.String>
        getSensorDotsList();
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @return The count of sensorDots.
     */
    int getSensorDotsCount();
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @param index The index of the element to return.
     * @return The sensorDots at the given index.
     */
    java.lang.String getSensorDots(int index);
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sensorDots at the given index.
     */
    com.google.protobuf.ByteString
        getSensorDotsBytes(int index);

    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    java.util.List<com.axxes.data.protos.PatientProtos.Annotation> 
        getAnnotationsList();
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    com.axxes.data.protos.PatientProtos.Annotation getAnnotations(int index);
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    java.util.List<? extends com.axxes.data.protos.PatientProtos.AnnotationOrBuilder> 
        getAnnotationsOrBuilderList();
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    com.axxes.data.protos.PatientProtos.AnnotationOrBuilder getAnnotationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Patient}
   */
  public static final class Patient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Patient)
      PatientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Patient.newBuilder() to construct.
    private Patient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Patient() {
      hospitalId_ = "";
      patientId_ = "";
      sensorDots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      annotations_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Patient();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Patient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hospitalId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                sensorDots_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              sensorDots_.add(s);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                annotations_ = new java.util.ArrayList<com.axxes.data.protos.PatientProtos.Annotation>();
                mutable_bitField0_ |= 0x00000002;
              }
              annotations_.add(
                  input.readMessage(com.axxes.data.protos.PatientProtos.Annotation.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          sensorDots_ = sensorDots_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          annotations_ = java.util.Collections.unmodifiableList(annotations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.axxes.data.protos.PatientProtos.internal_static_Patient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.axxes.data.protos.PatientProtos.internal_static_Patient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.axxes.data.protos.PatientProtos.Patient.class, com.axxes.data.protos.PatientProtos.Patient.Builder.class);
    }

    public static final int HOSPITALID_FIELD_NUMBER = 1;
    private volatile java.lang.Object hospitalId_;
    /**
     * <code>string hospitalId = 1;</code>
     * @return The hospitalId.
     */
    @java.lang.Override
    public java.lang.String getHospitalId() {
      java.lang.Object ref = hospitalId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hospitalId_ = s;
        return s;
      }
    }
    /**
     * <code>string hospitalId = 1;</code>
     * @return The bytes for hospitalId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHospitalIdBytes() {
      java.lang.Object ref = hospitalId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hospitalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATIENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patientId = 2;</code>
     * @return The patientId.
     */
    @java.lang.Override
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patientId = 2;</code>
     * @return The bytes for patientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSOR_DOTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList sensorDots_;
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @return A list containing the sensorDots.
     */
    public com.google.protobuf.ProtocolStringList
        getSensorDotsList() {
      return sensorDots_;
    }
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @return The count of sensorDots.
     */
    public int getSensorDotsCount() {
      return sensorDots_.size();
    }
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @param index The index of the element to return.
     * @return The sensorDots at the given index.
     */
    public java.lang.String getSensorDots(int index) {
      return sensorDots_.get(index);
    }
    /**
     * <code>repeated string sensor_dots = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sensorDots at the given index.
     */
    public com.google.protobuf.ByteString
        getSensorDotsBytes(int index) {
      return sensorDots_.getByteString(index);
    }

    public static final int ANNOTATIONS_FIELD_NUMBER = 4;
    private java.util.List<com.axxes.data.protos.PatientProtos.Annotation> annotations_;
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.axxes.data.protos.PatientProtos.Annotation> getAnnotationsList() {
      return annotations_;
    }
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.axxes.data.protos.PatientProtos.AnnotationOrBuilder> 
        getAnnotationsOrBuilderList() {
      return annotations_;
    }
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    @java.lang.Override
    public int getAnnotationsCount() {
      return annotations_.size();
    }
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    @java.lang.Override
    public com.axxes.data.protos.PatientProtos.Annotation getAnnotations(int index) {
      return annotations_.get(index);
    }
    /**
     * <code>repeated .Annotation annotations = 4;</code>
     */
    @java.lang.Override
    public com.axxes.data.protos.PatientProtos.AnnotationOrBuilder getAnnotationsOrBuilder(
        int index) {
      return annotations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hospitalId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hospitalId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, patientId_);
      }
      for (int i = 0; i < sensorDots_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sensorDots_.getRaw(i));
      }
      for (int i = 0; i < annotations_.size(); i++) {
        output.writeMessage(4, annotations_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hospitalId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hospitalId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, patientId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sensorDots_.size(); i++) {
          dataSize += computeStringSizeNoTag(sensorDots_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSensorDotsList().size();
      }
      for (int i = 0; i < annotations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, annotations_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.axxes.data.protos.PatientProtos.Patient)) {
        return super.equals(obj);
      }
      com.axxes.data.protos.PatientProtos.Patient other = (com.axxes.data.protos.PatientProtos.Patient) obj;

      if (!getHospitalId()
          .equals(other.getHospitalId())) return false;
      if (!getPatientId()
          .equals(other.getPatientId())) return false;
      if (!getSensorDotsList()
          .equals(other.getSensorDotsList())) return false;
      if (!getAnnotationsList()
          .equals(other.getAnnotationsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOSPITALID_FIELD_NUMBER;
      hash = (53 * hash) + getHospitalId().hashCode();
      hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      if (getSensorDotsCount() > 0) {
        hash = (37 * hash) + SENSOR_DOTS_FIELD_NUMBER;
        hash = (53 * hash) + getSensorDotsList().hashCode();
      }
      if (getAnnotationsCount() > 0) {
        hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getAnnotationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.axxes.data.protos.PatientProtos.Patient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.axxes.data.protos.PatientProtos.Patient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Patient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Patient)
        com.axxes.data.protos.PatientProtos.PatientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.axxes.data.protos.PatientProtos.internal_static_Patient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.axxes.data.protos.PatientProtos.internal_static_Patient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.axxes.data.protos.PatientProtos.Patient.class, com.axxes.data.protos.PatientProtos.Patient.Builder.class);
      }

      // Construct using com.axxes.data.protos.PatientProtos.Patient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAnnotationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hospitalId_ = "";

        patientId_ = "";

        sensorDots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (annotationsBuilder_ == null) {
          annotations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          annotationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.axxes.data.protos.PatientProtos.internal_static_Patient_descriptor;
      }

      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.Patient getDefaultInstanceForType() {
        return com.axxes.data.protos.PatientProtos.Patient.getDefaultInstance();
      }

      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.Patient build() {
        com.axxes.data.protos.PatientProtos.Patient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.axxes.data.protos.PatientProtos.Patient buildPartial() {
        com.axxes.data.protos.PatientProtos.Patient result = new com.axxes.data.protos.PatientProtos.Patient(this);
        int from_bitField0_ = bitField0_;
        result.hospitalId_ = hospitalId_;
        result.patientId_ = patientId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          sensorDots_ = sensorDots_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sensorDots_ = sensorDots_;
        if (annotationsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            annotations_ = java.util.Collections.unmodifiableList(annotations_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.annotations_ = annotations_;
        } else {
          result.annotations_ = annotationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.axxes.data.protos.PatientProtos.Patient) {
          return mergeFrom((com.axxes.data.protos.PatientProtos.Patient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.axxes.data.protos.PatientProtos.Patient other) {
        if (other == com.axxes.data.protos.PatientProtos.Patient.getDefaultInstance()) return this;
        if (!other.getHospitalId().isEmpty()) {
          hospitalId_ = other.hospitalId_;
          onChanged();
        }
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        if (!other.sensorDots_.isEmpty()) {
          if (sensorDots_.isEmpty()) {
            sensorDots_ = other.sensorDots_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSensorDotsIsMutable();
            sensorDots_.addAll(other.sensorDots_);
          }
          onChanged();
        }
        if (annotationsBuilder_ == null) {
          if (!other.annotations_.isEmpty()) {
            if (annotations_.isEmpty()) {
              annotations_ = other.annotations_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAnnotationsIsMutable();
              annotations_.addAll(other.annotations_);
            }
            onChanged();
          }
        } else {
          if (!other.annotations_.isEmpty()) {
            if (annotationsBuilder_.isEmpty()) {
              annotationsBuilder_.dispose();
              annotationsBuilder_ = null;
              annotations_ = other.annotations_;
              bitField0_ = (bitField0_ & ~0x00000002);
              annotationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAnnotationsFieldBuilder() : null;
            } else {
              annotationsBuilder_.addAllMessages(other.annotations_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.axxes.data.protos.PatientProtos.Patient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.axxes.data.protos.PatientProtos.Patient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object hospitalId_ = "";
      /**
       * <code>string hospitalId = 1;</code>
       * @return The hospitalId.
       */
      public java.lang.String getHospitalId() {
        java.lang.Object ref = hospitalId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hospitalId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hospitalId = 1;</code>
       * @return The bytes for hospitalId.
       */
      public com.google.protobuf.ByteString
          getHospitalIdBytes() {
        java.lang.Object ref = hospitalId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hospitalId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hospitalId = 1;</code>
       * @param value The hospitalId to set.
       * @return This builder for chaining.
       */
      public Builder setHospitalId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hospitalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hospitalId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHospitalId() {
        
        hospitalId_ = getDefaultInstance().getHospitalId();
        onChanged();
        return this;
      }
      /**
       * <code>string hospitalId = 1;</code>
       * @param value The bytes for hospitalId to set.
       * @return This builder for chaining.
       */
      public Builder setHospitalIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hospitalId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patientId = 2;</code>
       * @return The patientId.
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patientId = 2;</code>
       * @return The bytes for patientId.
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patientId = 2;</code>
       * @param value The patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patientId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patientId = 2;</code>
       * @param value The bytes for patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList sensorDots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSensorDotsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          sensorDots_ = new com.google.protobuf.LazyStringArrayList(sensorDots_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @return A list containing the sensorDots.
       */
      public com.google.protobuf.ProtocolStringList
          getSensorDotsList() {
        return sensorDots_.getUnmodifiableView();
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @return The count of sensorDots.
       */
      public int getSensorDotsCount() {
        return sensorDots_.size();
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @param index The index of the element to return.
       * @return The sensorDots at the given index.
       */
      public java.lang.String getSensorDots(int index) {
        return sensorDots_.get(index);
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the sensorDots at the given index.
       */
      public com.google.protobuf.ByteString
          getSensorDotsBytes(int index) {
        return sensorDots_.getByteString(index);
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @param index The index to set the value at.
       * @param value The sensorDots to set.
       * @return This builder for chaining.
       */
      public Builder setSensorDots(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSensorDotsIsMutable();
        sensorDots_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @param value The sensorDots to add.
       * @return This builder for chaining.
       */
      public Builder addSensorDots(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSensorDotsIsMutable();
        sensorDots_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @param values The sensorDots to add.
       * @return This builder for chaining.
       */
      public Builder addAllSensorDots(
          java.lang.Iterable<java.lang.String> values) {
        ensureSensorDotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sensorDots_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensorDots() {
        sensorDots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sensor_dots = 3;</code>
       * @param value The bytes of the sensorDots to add.
       * @return This builder for chaining.
       */
      public Builder addSensorDotsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSensorDotsIsMutable();
        sensorDots_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.axxes.data.protos.PatientProtos.Annotation> annotations_ =
        java.util.Collections.emptyList();
      private void ensureAnnotationsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          annotations_ = new java.util.ArrayList<com.axxes.data.protos.PatientProtos.Annotation>(annotations_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.axxes.data.protos.PatientProtos.Annotation, com.axxes.data.protos.PatientProtos.Annotation.Builder, com.axxes.data.protos.PatientProtos.AnnotationOrBuilder> annotationsBuilder_;

      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public java.util.List<com.axxes.data.protos.PatientProtos.Annotation> getAnnotationsList() {
        if (annotationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(annotations_);
        } else {
          return annotationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public int getAnnotationsCount() {
        if (annotationsBuilder_ == null) {
          return annotations_.size();
        } else {
          return annotationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public com.axxes.data.protos.PatientProtos.Annotation getAnnotations(int index) {
        if (annotationsBuilder_ == null) {
          return annotations_.get(index);
        } else {
          return annotationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder setAnnotations(
          int index, com.axxes.data.protos.PatientProtos.Annotation value) {
        if (annotationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnnotationsIsMutable();
          annotations_.set(index, value);
          onChanged();
        } else {
          annotationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder setAnnotations(
          int index, com.axxes.data.protos.PatientProtos.Annotation.Builder builderForValue) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.set(index, builderForValue.build());
          onChanged();
        } else {
          annotationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder addAnnotations(com.axxes.data.protos.PatientProtos.Annotation value) {
        if (annotationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnnotationsIsMutable();
          annotations_.add(value);
          onChanged();
        } else {
          annotationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder addAnnotations(
          int index, com.axxes.data.protos.PatientProtos.Annotation value) {
        if (annotationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnnotationsIsMutable();
          annotations_.add(index, value);
          onChanged();
        } else {
          annotationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder addAnnotations(
          com.axxes.data.protos.PatientProtos.Annotation.Builder builderForValue) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.add(builderForValue.build());
          onChanged();
        } else {
          annotationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder addAnnotations(
          int index, com.axxes.data.protos.PatientProtos.Annotation.Builder builderForValue) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.add(index, builderForValue.build());
          onChanged();
        } else {
          annotationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder addAllAnnotations(
          java.lang.Iterable<? extends com.axxes.data.protos.PatientProtos.Annotation> values) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, annotations_);
          onChanged();
        } else {
          annotationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder clearAnnotations() {
        if (annotationsBuilder_ == null) {
          annotations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          annotationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public Builder removeAnnotations(int index) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.remove(index);
          onChanged();
        } else {
          annotationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public com.axxes.data.protos.PatientProtos.Annotation.Builder getAnnotationsBuilder(
          int index) {
        return getAnnotationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public com.axxes.data.protos.PatientProtos.AnnotationOrBuilder getAnnotationsOrBuilder(
          int index) {
        if (annotationsBuilder_ == null) {
          return annotations_.get(index);  } else {
          return annotationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public java.util.List<? extends com.axxes.data.protos.PatientProtos.AnnotationOrBuilder> 
           getAnnotationsOrBuilderList() {
        if (annotationsBuilder_ != null) {
          return annotationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(annotations_);
        }
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public com.axxes.data.protos.PatientProtos.Annotation.Builder addAnnotationsBuilder() {
        return getAnnotationsFieldBuilder().addBuilder(
            com.axxes.data.protos.PatientProtos.Annotation.getDefaultInstance());
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public com.axxes.data.protos.PatientProtos.Annotation.Builder addAnnotationsBuilder(
          int index) {
        return getAnnotationsFieldBuilder().addBuilder(
            index, com.axxes.data.protos.PatientProtos.Annotation.getDefaultInstance());
      }
      /**
       * <code>repeated .Annotation annotations = 4;</code>
       */
      public java.util.List<com.axxes.data.protos.PatientProtos.Annotation.Builder> 
           getAnnotationsBuilderList() {
        return getAnnotationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.axxes.data.protos.PatientProtos.Annotation, com.axxes.data.protos.PatientProtos.Annotation.Builder, com.axxes.data.protos.PatientProtos.AnnotationOrBuilder> 
          getAnnotationsFieldBuilder() {
        if (annotationsBuilder_ == null) {
          annotationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.axxes.data.protos.PatientProtos.Annotation, com.axxes.data.protos.PatientProtos.Annotation.Builder, com.axxes.data.protos.PatientProtos.AnnotationOrBuilder>(
                  annotations_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          annotations_ = null;
        }
        return annotationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Patient)
    }

    // @@protoc_insertion_point(class_scope:Patient)
    private static final com.axxes.data.protos.PatientProtos.Patient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.axxes.data.protos.PatientProtos.Patient();
    }

    public static com.axxes.data.protos.PatientProtos.Patient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Patient>
        PARSER = new com.google.protobuf.AbstractParser<Patient>() {
      @java.lang.Override
      public Patient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Patient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Patient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Patient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.axxes.data.protos.PatientProtos.Patient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Annotation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Annotation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Patient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Patient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpatient.proto\"^\n\nAnnotation\022\n\n\002id\030\001 \001(" +
      "\t\022\r\n\005start\030\002 \001(\002\022\013\n\003end\030\003 \001(\002\022(\n\017annotat" +
      "ion_type\030\004 \001(\0162\017.AnnotationType\"g\n\007Patie" +
      "nt\022\022\n\nhospitalId\030\001 \001(\t\022\021\n\tpatientId\030\002 \001(" +
      "\t\022\023\n\013sensor_dots\030\003 \003(\t\022 \n\013annotations\030\004 " +
      "\003(\0132\013.Annotation*;\n\016AnnotationType\022\010\n\004af" +
      "ib\020\000\022\t\n\005pause\020\001\022\t\n\005brady\020\002\022\t\n\005tachy\020\003B&\n" +
      "\025com.axxes.data.protosB\rPatientProtosb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Annotation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Annotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Annotation_descriptor,
        new java.lang.String[] { "Id", "Start", "End", "AnnotationType", });
    internal_static_Patient_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Patient_descriptor,
        new java.lang.String[] { "HospitalId", "PatientId", "SensorDots", "Annotations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
